server:
  port: 8761
eureka:
  client:
    service-url:
      # Comma separated list
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
spring:
  application:
    name: eurekaserver